### ISSUE TITLE
Mousai Failed running on ubuntu 22 LTS

### ISSUE THREAD

**Issue by joshuakawalya766** [SeaDve/Mousai#111] opened 2023-12-01 09:11 UTC
- io.github.seadve.Mousai 0.7.5
- Flatpak: false

- Language: en_US.UTF-8, en_US, en.UTF-8, en, C

- Distribution: Ubuntu Core 22
- Desktop Session: ubuntu-xorg
- Display Server: x11

- GTK 4.12.2
- Libadwaita 1.4.0
- Libsoup 3.4.3
- GStreamer 1.20.3

**Comment by SeaDve** [comment] 2023-12-01 09:18
Hi, thanks for the report! However, it is pretty difficult to narrow down the error source, without having the actual errors you had why it "Failed running". You can provide terminal logs, how can I reproduce the error, what happened, and what did you expect to happen instead.

**Comment by soumyaDghosh** [comment] 2024-01-21 18:06
@joshuakawalya766 You probably don't have portals installed in your Ubuntu 22.04 LTS, can you try this and say if it's working?

```bash
sudo apt install xdg-desktop-portal-gnome xdg-desktop-portal-gtk
```

after restarting try, if it again fails to launch, kindly share the output of 

```bash
snap version && snap info mousai && snap connections mousai && snap run mousai
```

**Comment by SeaDve** [comment] 2024-01-27 12:07
I'm gonna close this for now since the information given does not give much context or the problem. Feel free to re-open it though with the required information. Thanks!

**Closed by SeaDve** 2024-01-27 12:07 UTC
Labels: Needs information
