### ISSUE TITLE
mousai is not listen to any music

### ISSUE THREAD

**Issue by smarthaleem** [SeaDve/Mousai#96] opened 2023-08-05 14:42 UTC
**Affected version**

**Bug summary**

**Steps to reproduce**

**Expected behavior**

**Relevant logs, screenshots, screencasts, etc.**

**Comment by SeaDve** [comment] 2023-08-06 04:12
I assume this is duplicate of succeeding issue

**Closed by SeaDve** 2023-08-06 04:12 UTC
